services:
  - type: web
    name: elevenlabs-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: ELEVEN_API_KEY
        value: "sk_26cb13ce52e950e595792b779d9ff5b8a37dcc786118f338"
